# SQLite can't handle most of the  below datatypes.
# We convert them to text or remove them entirely as needed. 
[standard_replacements]
"DEFAULT public.uuid_generate_v4()" = ""
"DEFAULT 0" = ""
"DEFAULT gen_random_uuid()" = ""
"DEFAULT now()" = ""
"uuid[]" = "text"
"text[]" = "text"
"jsonb[]" = "text"
"public." = ""
"uuid" = "text"
"timestamp without time zone" = "text"
"numeric" = "text"
"boolean" = "text"
"integer" = "text"
"jsonb" = "text"
"timestamp with time zone" = "text"


# My database has columns that aren't handled locally.
# The cloud API handles inserted_at and updated_at
# So they're null in the local db, until the cloud sync updates them.
[custom_replacements]
"inserted_at text NOT NULL" = "inserted_at text"
"updated_at text NOT NULL" = "updated_at text"
"::text" = ""
"charge_type text DEFAULT 'one_time' NOT NULL," = "charge_type text"
"CONSTRAINT billing_item_pricebook_charge_type_check CHECK ((charge_type = ANY (ARRAY['one_time', 'recurring'])))" = ""

[excluded_tables]
names = [
    "billing_audit_log", "billing_customer_nonsaas_items", "billing_customer_saas_rates", "billing_customer_stores", "billing_customers", "billing_headers",
    "billing_item_pricebook", "billing_items", "billing_location_information",
    "iso_resource_links", "iso_resource_sections",
    "kb_articles", "kb_categories", "kb_images", 
    "lambda_errors",
    "multiuser_log", "multiuser_stores", "multiuser_users",
    "onboarding_stores",
    "report_scheduler",
    "ref_hardware_solutions", "ref_dashboard_widgets", 
    "support_audit_log", "support_external_links", "support_users", "web_customer_stores", 
    "web_customers", "web_password_reset_tokens", "web_personas",
]